# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: rsschoolproject
# "service" is the name of this project. This will also be added to your AWS resource names.
service: product-service

provider:
  name: aws
  stage: dev
  region: us-east-1
  runtime: nodejs20.x

functions:
  getProductsList:
    handler: handler.getProductsList
    events:
      - httpApi:
          path: /products
          method: get
  getProductsById:
    handler: handler.getProductsById
    events:
      - httpApi:
          path: /products/{productId}
          method: get
